name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      with:
        fetch-depth: 0 # GitVersion is somewhat irritated when fetch-depth is "1"....
        ref: ${{ github.event.ref }}
    
    - name: Cache Tools
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentaiton
      uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        cake-version: 1.3.0
